Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> >>> >>> >>> 
>>> 
>>> (lambda x: 2*x)(3)
6
>>> f= (lambda x: 2*x)(3)
>>> f(3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'int' object is not callable
>>> f= (lambda x: 2*x)
>>> f(3)
6
>>> lf = [lambda x: x*x, lambda x : 2*x]
>>> [f(3) for f in lf]
[9, 6]
>>> lf
[<function <lambda> at 0x7fa511fd2c80>, <function <lambda> at 0x7fa511fd2cf8>]
>>> type([1,2,3])
<type 'list'>
>>> lf
[<function <lambda> at 0x7fa511fd2c80>, <function <lambda> at 0x7fa511fd2cf8>]
>>> type(lf)
<type 'list'>
>>> lf
[<function <lambda> at 0x7fa511fd2c80>, <function <lambda> at 0x7fa511fd2cf8>]
>>> lf
[<function <lambda> at 0x7fa511fd2c80>, <function <lambda> at 0x7fa511fd2cf8>]
>>> lf + ["abc",1]
[<function <lambda> at 0x7fa511fd2c80>, <function <lambda> at 0x7fa511fd2cf8>, 'abc', 1]
>>> 3(2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'int' object is not callable
>>> 